/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 
//importa el paquete views de la interfaz
package Views.interfaz;


//añade las librerias de java
import otros.Conectado_db;
import java.sql.*;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juan
 */
public class Formulario_empleado extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Formulario_empleado() {
        initComponents();
        login.setVisible(false);
        registro.setVisible(false);
        secretaria.setVisible(false);
        gerente.setVisible(false);
        Mail.setVisible(false);
        registrarse.setVisible(true);
        CRUD.setVisible(false);
    }
    //crea la instancia 
    Calendar MiCalendario = Calendar.getInstance();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registro = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        secretaria = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        login = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton15 = new javax.swing.JButton();
        gerente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        Mail = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton12 = new javax.swing.JButton();
        registrarse = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton17 = new javax.swing.JButton();
        CRUD = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(null);

        registro.setBackground(new java.awt.Color(29, 133, 238));
        registro.setLayout(null);

        jButton1.setText("Secretaria");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        registro.add(jButton1);
        jButton1.setBounds(50, 70, 130, 80);

        jButton2.setText("gerente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        registro.add(jButton2);
        jButton2.setBounds(50, 300, 130, 70);

        jButton7.setText("Ingresar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        registro.add(jButton7);
        jButton7.setBounds(50, 180, 130, 80);

        jButton11.setText("Enviar Mail");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        registro.add(jButton11);
        jButton11.setBounds(50, 400, 130, 80);

        getContentPane().add(registro);
        registro.setBounds(0, 0, 800, 800);

        secretaria.setBackground(new java.awt.Color(153, 204, 255));
        secretaria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        secretaria.setToolTipText("");
        secretaria.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                secretariaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        secretaria.setLayout(null);

        jLabel1.setText("ID");
        secretaria.add(jLabel1);
        jLabel1.setBounds(100, 70, 30, 17);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        secretaria.add(jTextField1);
        jTextField1.setBounds(290, 70, 300, 30);

        jLabel2.setText("NOMBRE");
        secretaria.add(jLabel2);
        jLabel2.setBounds(100, 150, 70, 17);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        secretaria.add(jTextField2);
        jTextField2.setBounds(290, 140, 300, 30);

        jLabel3.setText("CARGO");
        secretaria.add(jLabel3);
        jLabel3.setBounds(100, 240, 50, 17);

        jLabel4.setText("SALARIO");
        secretaria.add(jLabel4);
        jLabel4.setBounds(100, 310, 90, 17);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        secretaria.add(jTextField3);
        jTextField3.setBounds(290, 220, 300, 30);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        secretaria.add(jTextField4);
        jTextField4.setBounds(290, 290, 300, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save.jpeg"))); // NOI18N
        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        secretaria.add(jButton3);
        jButton3.setBounds(180, 430, 150, 60);

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        jButton13.setText("Salir");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        secretaria.add(jButton13);
        jButton13.setBounds(390, 430, 140, 60);

        getContentPane().add(secretaria);
        secretaria.setBounds(0, 0, 840, 570);

        login.setBackground(new java.awt.Color(97, 192, 244));
        login.setMinimumSize(new java.awt.Dimension(700, 500));
        login.setPreferredSize(new java.awt.Dimension(650, 620));
        login.setLayout(null);

        jLabel5.setForeground(new java.awt.Color(29, 17, 17));
        jLabel5.setText("USUARIO");
        login.add(jLabel5);
        jLabel5.setBounds(210, 110, 70, 17);

        jLabel6.setForeground(new java.awt.Color(20, 6, 6));
        jLabel6.setText("CLAVE");
        login.add(jLabel6);
        jLabel6.setBounds(210, 230, 60, 17);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        login.add(jTextField7);
        jTextField7.setBounds(210, 140, 300, 40);

        jButton8.setText("ENTRAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        login.add(jButton8);
        jButton8.setBounds(210, 390, 310, 40);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        login.add(jPasswordField1);
        jPasswordField1.setBounds(210, 270, 300, 40);

        jButton15.setText("registarse");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        login.add(jButton15);
        jButton15.setBounds(210, 460, 310, 50);

        getContentPane().add(login);
        login.setBounds(0, 10, 790, 700);

        gerente.setBackground(new java.awt.Color(155, 229, 235));
        gerente.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CARGO", "SALARIO"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setEnabled(false);
        jTable1.setFocusCycleRoot(true);
        jTable1.setGridColor(new java.awt.Color(154, 146, 146));
        jTable1.setRequestFocusEnabled(false);
        jTable1.setSurrendersFocusOnKeystroke(true);
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gerente.add(jScrollPane1);
        jScrollPane1.setBounds(50, 50, 550, 210);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login.png"))); // NOI18N
        jButton4.setText("ver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gerente.add(jButton4);
        jButton4.setBounds(470, 330, 130, 60);
        gerente.add(jTextField5);
        jTextField5.setBounds(46, 320, 150, 27);

        jButton5.setText("Buscar por nombre");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gerente.add(jButton5);
        jButton5.setBounds(220, 320, 160, 29);
        gerente.add(jTextField6);
        jTextField6.setBounds(50, 370, 150, 27);

        jButton6.setText("Buscar por ID");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gerente.add(jButton6);
        jButton6.setBounds(220, 370, 160, 29);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/exit.png"))); // NOI18N
        jButton9.setText("Salir");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gerente.add(jButton9);
        jButton9.setBounds(470, 420, 130, 60);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gerente\t", "Secretaria" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gerente.add(jComboBox1);
        jComboBox1.setBounds(180, 460, 180, 27);

        jLabel7.setText("seleccione rol");
        gerente.add(jLabel7);
        jLabel7.setBounds(50, 470, 110, 17);

        jButton21.setText("Actualizar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        gerente.add(jButton21);
        jButton21.setBounds(470, 500, 130, 60);

        jButton22.setText("Eliminar");
        gerente.add(jButton22);
        jButton22.setBounds(470, 580, 130, 60);

        getContentPane().add(gerente);
        gerente.setBounds(60, 50, 660, 1000);

        Mail.setLayout(null);

        jLabel8.setText("Desde");
        Mail.add(jLabel8);
        jLabel8.setBounds(40, 110, 120, 17);

        jLabel9.setText("Para");
        Mail.add(jLabel9);
        jLabel9.setBounds(40, 170, 31, 17);

        jLabel10.setText("Asunto");
        Mail.add(jLabel10);
        jLabel10.setBounds(40, 220, 49, 17);

        jTextField8.setText("jTextField8");
        Mail.add(jTextField8);
        jTextField8.setBounds(160, 110, 320, 27);

        jTextField9.setText("jTextField9");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        Mail.add(jTextField9);
        jTextField9.setBounds(160, 160, 320, 27);

        jTextField10.setText("jTextField10");
        Mail.add(jTextField10);
        jTextField10.setBounds(160, 210, 320, 27);

        jButton10.setText("Enviar");
        Mail.add(jButton10);
        jButton10.setBounds(510, 100, 150, 140);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        Mail.add(jScrollPane2);
        jScrollPane2.setBounds(40, 270, 620, 200);

        jLabel11.setText("seleccione rol");
        Mail.add(jLabel11);
        jLabel11.setBounds(40, 30, 110, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gerente\t", "Secretaria" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        Mail.add(jComboBox2);
        jComboBox2.setBounds(180, 30, 210, 27);

        jButton12.setText("Salir");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Mail.add(jButton12);
        jButton12.setBounds(580, 490, 80, 29);

        getContentPane().add(Mail);
        Mail.setBounds(0, 0, 700, 540);

        registrarse.setBackground(new java.awt.Color(137, 211, 251));
        registrarse.setLayout(null);

        jLabel12.setText("ROL");
        registrarse.add(jLabel12);
        jLabel12.setBounds(120, 90, 40, 17);

        jLabel13.setText("NOMBRES");
        registrarse.add(jLabel13);
        jLabel13.setBounds(120, 160, 80, 20);

        jLabel14.setText("MAIL");
        registrarse.add(jLabel14);
        jLabel14.setBounds(120, 220, 33, 17);

        jLabel15.setText("TELEFONO");
        registrarse.add(jLabel15);
        jLabel15.setBounds(120, 270, 80, 17);

        jLabel16.setText("USUARIO");
        registrarse.add(jLabel16);
        jLabel16.setBounds(120, 330, 70, 17);

        jLabel17.setText("CONTRASEÑA");
        registrarse.add(jLabel17);
        jLabel17.setBounds(120, 400, 100, 17);

        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });
        registrarse.add(jTextField12);
        jTextField12.setBounds(290, 150, 310, 27);

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        registrarse.add(jTextField13);
        jTextField13.setBounds(290, 210, 310, 27);
        registrarse.add(jTextField14);
        jTextField14.setBounds(290, 260, 310, 27);
        registrarse.add(jTextField15);
        jTextField15.setBounds(290, 320, 310, 27);

        jButton16.setText("REGISTRARSE");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        registrarse.add(jButton16);
        jButton16.setBounds(200, 470, 140, 60);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Secretaria", "Gerente" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        registrarse.add(jComboBox3);
        jComboBox3.setBounds(290, 80, 310, 27);
        registrarse.add(jPasswordField2);
        jPasswordField2.setBounds(290, 390, 310, 27);

        jButton17.setText("INGRESAR");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        registrarse.add(jButton17);
        jButton17.setBounds(390, 470, 140, 60);

        getContentPane().add(registrarse);
        registrarse.setBounds(0, 0, 740, 570);

        CRUD.setLayout(null);

        jButton14.setText("ACTUALIZAR");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        CRUD.add(jButton14);
        jButton14.setBounds(120, 310, 200, 110);

        jButton18.setText("ELIMINAR");
        CRUD.add(jButton18);
        jButton18.setBounds(390, 310, 180, 110);

        jButton19.setText("MOSTRAR");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        CRUD.add(jButton19);
        jButton19.setBounds(120, 160, 200, 110);

        jButton20.setText("CONSULTAR");
        CRUD.add(jButton20);
        jButton20.setBounds(390, 160, 180, 110);

        getContentPane().add(CRUD);
        CRUD.setBounds(0, 0, 700, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();

        if (jTextField1.getText().trim().isEmpty() || jTextField2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese los valores");
        } else {
            try {
                Statement stmt = cn.createStatement();
                String ins = "INSERT INTO NOMINA VALUES(" + jTextField1.getText() + ",'" + jTextField2.getText() + "','" + jTextField3.getText() + "'," + jTextField4.getText() + ");";
                int r = stmt.executeUpdate(ins);
            } catch (SQLException sqle) {
                JOptionPane.showMessageDialog(null, "Error al actualizar el registro");
            }

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            System.out.println("Accion" + "guarda los datos del empleado");
            System.out.println("Usuario: secretaria");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        secretaria.setVisible(true);
        gerente.setVisible(false);
        registro.setVisible(false);
        Mail.setVisible(false);

        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("Accion: " + "La secretaria ingresa a registrar los empleados");
        System.out.println("Usuario: secretaria");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        gerente.setVisible(true);
        login.setVisible(false);
        registro.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        try {
            Conectado_db sqlite = new Conectado_db();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String vt = null;
            vt = "SELECT * FROM nomina;";

            rs = stmt.executeQuery(vt);

            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            Object[] filas = new Object[jTable1.getColumnCount()];

            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(i);
            }
            //ciclo que recorre las posiciones de la columna de la tabla 
            while (rs.next()) {
                filas[0] = rs.getInt(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getInt(4);

                tableModel.addRow(filas);
            }
            rs.close();
            stmt.close();
            cn.close();
            Calendar MiCalendario = Calendar.getInstance();

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            System.out.println("Accion:" + "el usuario consulta los datos");
            System.out.println("Usuario: gerente");

        } catch (SQLException sq2) {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "No se pudo consultar",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Conectado_db sqlite = new Conectado_db();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            String busquedaSQL = "SELECT * FROM nomina WHERE NOMBRE = '" + jTextField5.getText() + "';";

            rs = stmt.executeQuery(busquedaSQL);

            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            Object[] filas = new Object[jTable1.getColumnCount()];

            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(i);
            }

            while (rs.next()) {

                filas[0] = rs.getInt(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getInt(4);

                tableModel.addRow(filas);
            }
            rs.close();
            stmt.close();
            cn.close();

            Date d = new Date();
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            System.out.println("Accion:" + "El usuario consulta el campo por nombre");
            System.out.println("Usuario: Gerente");

        } catch (SQLException sq2) {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "No se pudo consultar",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        try {
            Conectado_db sqlite = new Conectado_db();
            Connection cn = sqlite.Conectar();
            Statement stmt = cn.createStatement();
            ResultSet rs;
            //funcion de sql que hace la busqueda por id en el jtextfield 
            String busquedaSQL = "SELECT * FROM nomina WHERE ID = '" + jTextField6.getText() + "';";

            rs = stmt.executeQuery(busquedaSQL);

            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            Object[] filas = new Object[jTable1.getColumnCount()];

            for (int i = jTable1.getRowCount() - 1; i >= 0; i--) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(i);
            }

            while (rs.next()) {

                filas[0] = rs.getInt(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getInt(4);

                tableModel.addRow(filas);

            }
            rs.close();
            stmt.close();
            cn.close();
            Calendar MiCalendario = Calendar.getInstance();
            Date d = new Date();
            System.out.println("Accion:" + "El usuario consulta el campo por ID");
            System.out.println("Usuario: Gerente");
            System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
            System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

        } catch (SQLException sq2) {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "No se pudo consultar",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        gerente.setVisible(false);
        secretaria.setVisible(false);
        login.setVisible(true);
        registro.setVisible(false);

        Date d = new Date();
        System.out.println("Ingreso el usuario secreria al sistema");
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();

        String user = jTextField7.getText();
        char[] ps = jPasswordField1.getPassword();
        String password = new String(ps);
        String rol = null;

        try {
            Statement stmt = cn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM ROLES");

            while (rs.next()) {
                if (user.equals(rs.getString(2)) && password.equals(rs.getString(3))) {
                    rol = rs.getString(1);

                    if (rol.equals("Gerente")) {
                        login.setVisible(false);
                        gerente.setVisible(true);
                        registro.setVisible(false);

                    } else if (rol.equals("secretaria")) {
                        login.setVisible(false);
                        gerente.setVisible(false);
                        secretaria.setVisible(true);
                        registro.setVisible(false);
                        Mail.setVisible(false);

                    }
                }

            }

        } catch (SQLException sqex) {
            JOptionPane.showMessageDialog(null, "Acceso denegado:\n" + "No se pudo consultar",
                    "Acceso denegado", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this,
                "Esta seguro que desea salir?", "Confirmación",
                JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
            login.setVisible(false);
            registro.setVisible(true);
            gerente.setVisible(false);
        }


    }//GEN-LAST:event_jButton9ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() == 0) {
            gerente.setVisible(true);
        } else if (jComboBox1.getSelectedIndex() == 1) {
            registro.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Mail.setVisible(true);
        login.setVisible(false);
        registro.setVisible(false);
        gerente.setVisible(false);
        secretaria.setVisible(false);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void secretariaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_secretariaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_secretariaAncestorAdded

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if (jComboBox1.getSelectedIndex() == 0) {
            gerente.setVisible(true);
        } else if (jComboBox1.getSelectedIndex() == 1) {
            registro.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        secretaria.setVisible(true);

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        login.setVisible(true);
        secretaria.setVisible(false);
        registro.setVisible(false);
        gerente.setVisible(false);

        Calendar MiCalendario = Calendar.getInstance();
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("la secretaria se desconecto del sistema");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();

        if (jTextField12.getText().trim().isEmpty() || jTextField13.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese los valores");
        } else {

            try {
                Statement stmt = cn.createStatement();
                String ins = "INSERT INTO REGISTRAR VALUES(" + jTextField12.getText() + ",'" + jTextField13.getText() + "','" + jTextField14.getText() + "'," + ");";
                int r = stmt.executeUpdate(ins);

            } catch (SQLException sqle) {
                JOptionPane.showMessageDialog(null, "Error, al registrar");
            }

            try {
                String combox;
                combox = (String) jComboBox3.getSelectedItem();
                Statement stmt = cn.createStatement();
                String ins = "INSERT INTO ROLES VALUES(" + jTextField15.getText() + ",'" + jPasswordField2.getText() + "','" + combox + "'," + ");";
                int r = stmt.executeUpdate(ins);

            } catch (SQLException sqle) {
                JOptionPane.showMessageDialog(null, "Error, al registrar");
            }
        }

        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

    }//GEN-LAST:event_jButton16ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        registrarse.setVisible(true);
        registro.setVisible(false);
        gerente.setVisible(false);
        secretaria.setVisible(false);

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        login.setVisible(true);
        registrarse.setVisible(false);
        secretaria.setVisible(false);
        gerente.setVisible(false);
        registro.setVisible(false);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();
        try {
            Statement stmt = cn.createStatement();
            String ins = "UPDATE NOMINA SET NOMBRE(" + jTextField1.getText() + ",'" + jTextField2.getText() + "','" + jTextField3.getText() + "'," + jTextField4.getText() + ");";
            int r = stmt.executeUpdate(ins);

        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el registro");
        }

        gerente.setVisible(true);
        
        /**
         * realiza el log de registro del usuario
         */ 
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("Accion" + "guarda los datos del empleado");
        System.out.println("Usuario: secretaria");
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        secretaria.setVisible(true);

        Conectado_db sqlite = new Conectado_db();
        Connection cn = sqlite.Conectar();
        try {
            Statement stmt = cn.createStatement();
            String ins = "UPDATE SET NOMINA VALUES(" + jTextField1.getText() + ",'" + jTextField2.getText() + "','" + jTextField3.getText() + "'," + jTextField4.getText() + ");";
            int r = stmt.executeUpdate(ins);

        } catch (SQLException sqle) {
            JOptionPane.showMessageDialog(null, "Error al actualizar el registro");
        }

        gerente.setVisible(true);
        
        
        /**
         * realiza el log de registro del usuario
         */    
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("Accion" + "guarda los datos del empleado");
        System.out.println("Usuario: secretaria");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo Letras");

        }
    }//GEN-LAST:event_jTextField12KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo Letras");

        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if (Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo Letras");

        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo numeros");

        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();

        if (Character.isLetter(c)) {
            getToolkit().beep();

            evt.consume();

            JOptionPane.showMessageDialog(null, "Solo numeros");

        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario_empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CRUD;
    private javax.swing.JPanel Mail;
    private javax.swing.JPanel gerente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel login;
    private javax.swing.JPanel registrarse;
    private javax.swing.JPanel registro;
    private javax.swing.JPanel secretaria;
    // End of variables declaration//GEN-END:variables
}
